services:
  dustbin-verification-worker:
    build:
      context: .
      dockerfile: docker/dockerfiles/Dockerfile.worker
    container_name: axiom-dustbin-verification
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/gcp/axiom-flow-gcs-key.json
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      db:
         condition: service_healthy
    volumes:
      - dicom_dustbin:/dicom_data/dustbin
      - ./axiom-flow-gcs-key.json:/etc/gcp/axiom-flow-gcs-key.json:ro
    command: ["python", "-m", "app.worker.dustbin_verification_worker"]
    restart: unless-stopped
    networks:
      - default
      - shared
    logging:
      driver: "fluentd"
      options:
        mode: non-blocking
        max-buffer-size: "10m"
        fluentd-retry-wait: "1s"
        fluentd-max-retries: "60"
        fluentd-address: "127.0.0.1:24224"
        tag: "axiom.dustbin-verification.{{.Name}}"
