
# Dockerfile for the pynetdicom sender
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app/app

# Set the entrypoint to run the sender script as a module
CMD ["python", "-u", "-m", "app.senders.pynetdicom_sender"]
