"""remove_duplicate_timestamp_columns_use_base_class

Revision ID: 039ffd49045b
Revises: a70416b25485
Create Date: 2025-09-03 04:09:04.349855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '039ffd49045b'
down_revision: Union[str, None] = 'a70416b25485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_analytics_configs', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_log_analytics_configs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_analytics_configs_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('log_archival_rules', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_log_archival_rules_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_archival_rules_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('log_retention_policies', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_log_retention_policies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_retention_policies_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_retention_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_retention_policies_updated_at'))
        batch_op.drop_index(batch_op.f('ix_log_retention_policies_created_at'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('log_archival_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_archival_rules_updated_at'))
        batch_op.drop_index(batch_op.f('ix_log_archival_rules_created_at'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('log_analytics_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_analytics_configs_updated_at'))
        batch_op.drop_index(batch_op.f('ix_log_analytics_configs_created_at'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    # ### end Alembic commands ###
