"""add google healthcare source model

Revision ID: 1221285d9942
Revises: 6be745397cca
Create Date: 2025-05-04 19:10:59.136994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1221285d9942'
down_revision: Union[str, None] = '6be745397cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_healthcare_sources', schema=None) as batch_op:
        batch_op.drop_index('ix_google_healthcare_sources_created_at')
        batch_op.drop_index('ix_google_healthcare_sources_id')
        batch_op.drop_index('ix_google_healthcare_sources_name')
        batch_op.drop_index('ix_google_healthcare_sources_updated_at')

    op.drop_table('google_healthcare_sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_healthcare_sources',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gcp_project_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gcp_location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gcp_dataset_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gcp_dicom_store_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('polling_interval_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('query_filters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_google_healthcare_sources')
    )
    with op.batch_alter_table('google_healthcare_sources', schema=None) as batch_op:
        batch_op.create_index('ix_google_healthcare_sources_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_google_healthcare_sources_name', ['name'], unique=True)
        batch_op.create_index('ix_google_healthcare_sources_id', ['id'], unique=False)
        batch_op.create_index('ix_google_healthcare_sources_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###
