"""add_bypass_ip_validation_to_modalities

Revision ID: 123456789abc
Revises: c846df62bded
Create Date: 2025-08-10 21:28:19.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123456789abc'
down_revision = 'c846df62bded'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modalities', sa.Column('bypass_ip_validation', sa.Boolean(), nullable=False, server_default='false', comment='Whether this modality can bypass IP address validation (for testing/containers).'))
    op.create_index(op.f('ix_modalities_bypass_ip_validation'), 'modalities', ['bypass_ip_validation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modalities_bypass_ip_validation'), table_name='modalities')
    op.drop_column('modalities', 'bypass_ip_validation')
    # ### end Alembic commands ###
