"""Add listener_type to dimse_listener_configs

Revision ID: 129692e27a61
Revises: e8f2c9d41b7a
Create Date: 2025-08-13 18:42:45.453594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129692e27a61'
down_revision: Union[str, None] = 'e8f2c9d41b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimse_listener_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listener_type', sa.String(length=50), server_default=sa.text("'pynetdicom'"), nullable=False, comment="The type of listener implementation to use ('pynetdicom' or 'dcm4che')."))
        batch_op.create_index(batch_op.f('ix_dimse_listener_configs_listener_type'), ['listener_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimse_listener_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dimse_listener_configs_listener_type'))
        batch_op.drop_column('listener_type')

    # ### end Alembic commands ###
