"""fix_maintenance_bigint_fields

Revision ID: 147558378ec4
Revises: a38169bd65cd
Create Date: 2025-08-20 01:47:44.898021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147558378ec4'
down_revision: Union[str, None] = 'a38169bd65cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_cleaner_configs', schema=None) as batch_op:
        batch_op.alter_column('high_water_mark_bytes',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Maximum bytes to keep (for high_water_mark mode)',
               existing_nullable=True)

    with op.batch_alter_table('maintenance_tasks', schema=None) as batch_op:
        batch_op.alter_column('bytes_freed',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Bytes freed in this run',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_tasks', schema=None) as batch_op:
        batch_op.alter_column('bytes_freed',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Bytes freed in this run',
               existing_nullable=False)

    with op.batch_alter_table('data_cleaner_configs', schema=None) as batch_op:
        batch_op.alter_column('high_water_mark_bytes',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Maximum bytes to keep (for high_water_mark mode)',
               existing_nullable=True)

    # ### end Alembic commands ###
