"""update_for_is_active_poller_2

Revision ID: 157d53a9f5e7
Revises: 373d82d50d2d
Create Date: 2025-04-29 03:58:40.551337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157d53a9f5e7'
down_revision: Union[str, None] = '373d82d50d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dicomweb_source_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Whether AUTOMATIC polling for this source is active based on its schedule.'))
        batch_op.alter_column('is_enabled',
               existing_type=sa.BOOLEAN(),
               comment='Whether this source configuration is generally enabled and available (e.g., for data browser).',
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_dicomweb_source_state_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_dicomweb_source_state_is_enabled'), ['is_enabled'], unique=False)

    with op.batch_alter_table('dimse_qr_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Whether AUTOMATIC polling for this source is active based on its schedule.'))
        batch_op.alter_column('is_enabled',
               existing_type=sa.BOOLEAN(),
               comment='Whether this source configuration is generally enabled and available (e.g., for data browser).',
               existing_comment='Whether polling this source is active.',
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_dimse_qr_sources_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimse_qr_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dimse_qr_sources_is_active'))
        batch_op.alter_column('is_enabled',
               existing_type=sa.BOOLEAN(),
               comment='Whether polling this source is active.',
               existing_comment='Whether this source configuration is generally enabled and available (e.g., for data browser).',
               existing_nullable=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('dicomweb_source_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dicomweb_source_state_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_dicomweb_source_state_is_active'))
        batch_op.alter_column('is_enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this source configuration is generally enabled and available (e.g., for data browser).',
               existing_nullable=False)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
