"""add_spanner_configuration_tables

Revision ID: 20a5e96f8a5a
Revises: c26a7d312d44
Create Date: 2025-08-11 17:15:26.989950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a5e96f8a5a'
down_revision: Union[str, None] = 'c26a7d312d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
