"""Add transfer_syntax_strategy and max_association_retries to CStoreBackendConfig

Revision ID: 20ccf26766b4
Revises: 039ffd49045b
Create Date: 2025-09-09 21:13:48.057248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20ccf26766b4'
down_revision: Union[str, None] = '039ffd49045b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('senders', schema=None) as batch_op:
        batch_op.drop_index('ix_senders_created_at')
        batch_op.drop_index('ix_senders_id')
        batch_op.drop_index('ix_senders_name')
        batch_op.drop_index('ix_senders_updated_at')

    op.drop_table('senders')
    with op.batch_alter_table('storage_backend_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transfer_syntax_strategy', sa.String(length=50), server_default='conservative', nullable=True, comment='Strategy for transfer syntax negotiation (pynetdicom only).'))
        batch_op.add_column(sa.Column('max_association_retries', sa.Integer(), server_default='3', nullable=True, comment='Max association retries with different strategies (pynetdicom only).'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_backend_configs', schema=None) as batch_op:
        batch_op.drop_column('max_association_retries')
        batch_op.drop_column('transfer_syntax_strategy')

    op.create_table('senders',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sender_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('local_ae_title', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_senders')
    )
    with op.batch_alter_table('senders', schema=None) as batch_op:
        batch_op.create_index('ix_senders_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_senders_name', ['name'], unique=True)
        batch_op.create_index('ix_senders_id', ['id'], unique=False)
        batch_op.create_index('ix_senders_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###
