"""Add scheduled_exam_datetime to imaging_orders

Revision ID: 221822a6a34b
Revises: fac90a3babbe
Create Date: 2025-07-25 17:31:30.148558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221822a6a34b'
down_revision: Union[str, None] = 'fac90a3babbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imaging_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_exam_datetime', sa.DateTime(timezone=True), nullable=True, comment='Datetime the exam is scheduled to take place (ORC.7 TQ.4).'))
        batch_op.create_index(batch_op.f('ix_imaging_orders_scheduled_exam_datetime'), ['scheduled_exam_datetime'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imaging_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imaging_orders_scheduled_exam_datetime'))
        batch_op.drop_column('scheduled_exam_datetime')

    # ### end Alembic commands ###
