"""updates_for_schedule

Revision ID: 373d82d50d2d
Revises: cb2389d5cc21
Create Date: 2025-04-27 05:27:20.059776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373d82d50d2d'
down_revision: Union[str, None] = 'cb2389d5cc21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', sa.Integer(), nullable=True, comment='Optional ID of the Schedule controlling when this rule is active.'))
        batch_op.create_index(batch_op.f('ix_rules_schedule_id'), ['schedule_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_rules_schedule_id_schedules'), 'schedules', ['schedule_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rules_schedule_id_schedules'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_rules_schedule_id'))
        batch_op.drop_column('schedule_id')

    # ### end Alembic commands ###
