"""remove_sop_instance_uid_unique_constraint

Revision ID: 382e61014c9d
Revises: eb10e5697bf5
Create Date: 2025-08-18 19:33:38.056782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '382e61014c9d'
down_revision: Union[str, None] = 'eb10e5697bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the unique constraint on sop_instance_uid
    op.drop_index('ix_exam_batch_instances_sop_instance_uid', table_name='exam_batch_instances')
    # Recreate the index without unique constraint
    op.create_index('ix_exam_batch_instances_sop_instance_uid', 'exam_batch_instances', ['sop_instance_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the non-unique index
    op.drop_index('ix_exam_batch_instances_sop_instance_uid', table_name='exam_batch_instances')
    # Recreate the unique index
    op.create_index('ix_exam_batch_instances_sop_instance_uid', 'exam_batch_instances', ['sop_instance_uid'], unique=True)
    # ### end Alembic commands ###
