"""Add exam batching tables

Revision ID: 44de9c86a2fd
Revises: 7203ee557a04
Create Date: 2025-08-17 22:02:49.212533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44de9c86a2fd'
down_revision: Union[str, None] = '7203ee557a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_instance_uid', sa.String(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False, server_default='PENDING'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['storage_backend_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_batches_id'), 'exam_batches', ['id'], unique=False)
    op.create_index(op.f('ix_exam_batches_status'), 'exam_batches', ['status'], unique=False)
    op.create_index(op.f('ix_exam_batches_study_instance_uid'), 'exam_batches', ['study_instance_uid'], unique=False)

    op.create_table('exam_batch_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('processed_filepath', sa.String(), nullable=False),
    sa.Column('sop_instance_uid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['exam_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_batch_instances_id'), 'exam_batch_instances', ['id'], unique=False)
    op.create_index(op.f('ix_exam_batch_instances_sop_instance_uid'), 'exam_batch_instances', ['sop_instance_uid'], unique=True)

    with op.batch_alter_table('senders', schema=None) as batch_op:
        batch_op.drop_index('ix_senders_created_at')
        batch_op.drop_index('ix_senders_id')
        batch_op.drop_index('ix_senders_name')
        batch_op.drop_index('ix_senders_updated_at')

    op.drop_table('senders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('senders',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sender_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('local_ae_title', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_senders')
    )
    with op.batch_alter_table('senders', schema=None) as batch_op:
        batch_op.create_index('ix_senders_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_senders_name', ['name'], unique=True)
        batch_op.create_index('ix_senders_id', ['id'], unique=False)
        batch_op.create_index('ix_senders_created_at', ['created_at'], unique=False)

    op.drop_index(op.f('ix_exam_batch_instances_sop_instance_uid'), table_name='exam_batch_instances')
    op.drop_index(op.f('ix_exam_batch_instances_id'), table_name='exam_batch_instances')
    op.drop_table('exam_batch_instances')
    op.drop_index(op.f('ix_exam_batches_study_instance_uid'), table_name='exam_batches')
    op.drop_index(op.f('ix_exam_batches_status'), table_name='exam_batches')
    op.drop_index(op.f('ix_exam_batches_id'), table_name='exam_batches')
    op.drop_table('exam_batches')

