"""Add dimse_listener_configs table

Revision ID: 45e099a0cac2
Revises: 8528c7296dbe
Create Date: 2025-04-23 02:06:02.813844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e099a0cac2'
down_revision: Union[str, None] = '8528c7296dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
