"""expand imaging order model with more hl7 fields

Revision ID: 5d9a5228ef42
Revises: 007744df92c5
Create Date: 2025-07-24 15:37:54.535964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9a5228ef42'
down_revision: Union[str, None] = '007744df92c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imaging_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_address', sa.Text(), nullable=True, comment="Patient's full address."))
        batch_op.add_column(sa.Column('patient_phone_number', sa.String(length=64), nullable=True, comment="Patient's primary phone number."))
        batch_op.add_column(sa.Column('patient_class', sa.String(length=16), nullable=True, comment='e.g., O (Outpatient), I (Inpatient). From PV1-2.'))
        batch_op.add_column(sa.Column('visit_number', sa.String(length=64), nullable=True, comment="Patient's visit/encounter number. From PV1-19."))
        batch_op.add_column(sa.Column('placer_group_number', sa.String(length=128), nullable=True, comment='Groups related orders together. From ORC-4.'))
        batch_op.add_column(sa.Column('attending_physician', sa.String(length=255), nullable=True, comment='Attending physician. From PV1-7.'))
        batch_op.add_column(sa.Column('source_sending_application', sa.String(length=255), nullable=True, comment='Sending application from MSH-3.'))
        batch_op.add_column(sa.Column('source_sending_facility', sa.String(length=255), nullable=True, comment='Sending facility from MSH-4.'))
        batch_op.add_column(sa.Column('source_receiving_application', sa.String(length=255), nullable=True, comment='Receiving application from MSH-5.'))
        batch_op.add_column(sa.Column('source_receiving_facility', sa.String(length=255), nullable=True, comment='Receiving facility from MSH-6.'))
        batch_op.add_column(sa.Column('source_message_control_id', sa.String(length=128), nullable=True, comment='Message Control ID from MSH-10.'))
        batch_op.create_index(batch_op.f('ix_imaging_orders_placer_group_number'), ['placer_group_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_imaging_orders_visit_number'), ['visit_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imaging_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imaging_orders_visit_number'))
        batch_op.drop_index(batch_op.f('ix_imaging_orders_placer_group_number'))
        batch_op.drop_column('source_message_control_id')
        batch_op.drop_column('source_receiving_facility')
        batch_op.drop_column('source_receiving_application')
        batch_op.drop_column('source_sending_facility')
        batch_op.drop_column('source_sending_application')
        batch_op.drop_column('attending_physician')
        batch_op.drop_column('placer_group_number')
        batch_op.drop_column('visit_number')
        batch_op.drop_column('patient_class')
        batch_op.drop_column('patient_phone_number')
        batch_op.drop_column('patient_address')

    # ### end Alembic commands ###
