"""Add metric counters to dimse_qr_sources table

Revision ID: 6985f7ce04bd
Revises: b8d2ec890ce4
Create Date: 2025-04-24 12:50:37.408807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6985f7ce04bd'
down_revision: Union[str, None] = 'b8d2ec890ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimse_qr_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('found_study_count', sa.Integer(), server_default='0', nullable=False, comment='Total count of unique studies found by C-FIND across all polls.'))
        batch_op.add_column(sa.Column('move_queued_study_count', sa.Integer(), server_default='0', nullable=False, comment='Total count of studies actually queued for C-MOVE retrieval.'))
        batch_op.add_column(sa.Column('processed_instance_count', sa.Integer(), server_default='0', nullable=False, comment='Total count of instances successfully processed after C-MOVE.'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimse_qr_sources', schema=None) as batch_op:
        batch_op.drop_column('processed_instance_count')
        batch_op.drop_column('move_queued_study_count')
        batch_op.drop_column('found_study_count')

    # ### end Alembic commands ###
