"""Add TLS fields Listener/RQ

Revision ID: 6be745397cca
Revises: b179fd2df5a9
Create Date: 2025-05-03 04:02:57.098226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be745397cca'
down_revision: Union[str, None] = 'b179fd2df5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimse_listener_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tls_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Enable TLS for incoming connections to this listener.'))
        batch_op.add_column(sa.Column('tls_cert_secret_name', sa.String(length=512), nullable=True, comment="REQUIRED if TLS enabled: Secret Manager resource name for the server's TLS certificate (PEM)."))
        batch_op.add_column(sa.Column('tls_key_secret_name', sa.String(length=512), nullable=True, comment="REQUIRED if TLS enabled: Secret Manager resource name for the server's TLS private key (PEM)."))
        batch_op.add_column(sa.Column('tls_ca_cert_secret_name', sa.String(length=512), nullable=True, comment='Optional (for mTLS): Secret Manager resource name for the CA certificate (PEM) used to verify client certificates.'))
        batch_op.create_index(batch_op.f('ix_dimse_listener_configs_tls_enabled'), ['tls_enabled'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimse_listener_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dimse_listener_configs_tls_enabled'))
        batch_op.drop_column('tls_ca_cert_secret_name')
        batch_op.drop_column('tls_key_secret_name')
        batch_op.drop_column('tls_cert_secret_name')
        batch_op.drop_column('tls_enabled')

    # ### end Alembic commands ###
