"""add sender fields to storage backends

Revision ID: 7203ee557a04
Revises: 7657adc4b10c
Create Date: 2025-08-14 19:36:20.099097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7203ee557a04'
down_revision: Union[str, None] = '7657adc4b10c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('senders', schema=None) as batch_op:
        batch_op.drop_index('ix_senders_id')
        batch_op.drop_index('ix_senders_name')

    op.drop_table('senders')
    with op.batch_alter_table('storage_backend_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_identifier', sa.String(length=100), nullable=True, comment='Identifier of the sender configuration to use for this destination.'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_backend_configs', schema=None) as batch_op:
        batch_op.drop_column('sender_identifier')

    op.create_table('senders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sender_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('local_ae_title', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_senders')
    )
    with op.batch_alter_table('senders', schema=None) as batch_op:
        batch_op.create_index('ix_senders_name', ['name'], unique=True)
        batch_op.create_index('ix_senders_id', ['id'], unique=False)

    # ### end Alembic commands ###
