"""Add sender_identifier to storage_backend_configs

Revision ID: 7657adc4b10c
Revises: 6aba87c35a99
Create Date: 2025-08-14 18:52:40.715953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7657adc4b10c'
down_revision: Union[str, None] = '6aba87c35a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
