"""add_rule_destination_m2m_relation

Revision ID: 7c0e2c7d380e
Revises: b812449db4a4
Create Date: 2025-04-24 20:42:34.769931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c0e2c7d380e'
down_revision: Union[str, None] = 'b812449db4a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_column('destinations')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destinations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='List of storage destination objects (validated by Pydantic)'))

    # ### end Alembic commands ###
