"""Add configuration fields to DicomWebSourceState

Revision ID: 8528c7296dbe
Revises: c2092b0e9b90
Create Date: 2025-04-22 01:09:23.364008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8528c7296dbe'
down_revision: Union[str, None] = 'c2092b0e9b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - ADJUSTED ###
    op.add_column('dicomweb_source_state', sa.Column('description', sa.Text(), nullable=True))
    # Added server_default for base_url
    op.add_column('dicomweb_source_state', sa.Column('base_url', sa.String(), nullable=False, server_default='http://placeholder.url'))
    # Added server_default for qido_prefix
    op.add_column('dicomweb_source_state', sa.Column('qido_prefix', sa.String(), nullable=False, server_default='qido-rs'))
    # Added server_default for wado_prefix
    op.add_column('dicomweb_source_state', sa.Column('wado_prefix', sa.String(), nullable=False, server_default='wado-rs'))
    # Added server_default for polling_interval_seconds (as string)
    op.add_column('dicomweb_source_state', sa.Column('polling_interval_seconds', sa.Integer(), nullable=False, server_default='300'))
    # Added server_default for auth_type
    op.add_column('dicomweb_source_state', sa.Column('auth_type', sa.String(length=50), nullable=False, server_default='none'))
    # Nullable columns don't need server_default for the ALTER TABLE itself
    op.add_column('dicomweb_source_state', sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('dicomweb_source_state', sa.Column('search_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dicomweb_source_state', 'search_filters')
    op.drop_column('dicomweb_source_state', 'auth_config')
    op.drop_column('dicomweb_source_state', 'auth_type')
    op.drop_column('dicomweb_source_state', 'polling_interval_seconds')
    op.drop_column('dicomweb_source_state', 'wado_prefix')
    op.drop_column('dicomweb_source_state', 'qido_prefix')
    op.drop_column('dicomweb_source_state', 'base_url')
    op.drop_column('dicomweb_source_state', 'description')
    # ### end Alembic commands ###
