"""Add dimse_listener_state table

Revision ID: 9aad7a0eb3e4
Revises: 5e340e6770de
Create Date: 2025-04-21 03:27:38.258672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9aad7a0eb3e4'
down_revision: Union[str, None] = '5e340e6770de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimse_listener_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listener_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('ae_title', sa.String(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dimse_listener_state'))
    )
    op.create_index(op.f('ix_dimse_listener_state_id'), 'dimse_listener_state', ['id'], unique=False)
    op.create_index(op.f('ix_dimse_listener_state_listener_id'), 'dimse_listener_state', ['listener_id'], unique=True)
    op.create_index(op.f('ix_dimse_listener_state_updated_at'), 'dimse_listener_state', ['updated_at'], unique=False)
    op.drop_index('ix_listener_state_id', table_name='listener_state')
    op.drop_index('ix_listener_state_listener_id', table_name='listener_state')
    op.drop_index('ix_listener_state_updated_at', table_name='listener_state')
    op.drop_table('listener_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listener_state',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('listener_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('host', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ae_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_heartbeat', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_listener_state')
    )
    op.create_index('ix_listener_state_updated_at', 'listener_state', ['updated_at'], unique=False)
    op.create_index('ix_listener_state_listener_id', 'listener_state', ['listener_id'], unique=True)
    op.create_index('ix_listener_state_id', 'listener_state', ['id'], unique=False)
    op.drop_index(op.f('ix_dimse_listener_state_updated_at'), table_name='dimse_listener_state')
    op.drop_index(op.f('ix_dimse_listener_state_listener_id'), table_name='dimse_listener_state')
    op.drop_index(op.f('ix_dimse_listener_state_id'), table_name='dimse_listener_state')
    op.drop_table('dimse_listener_state')
    # ### end Alembic commands ###
