"""Fix system_settings primary key schema

Revision ID: 9e323e9873e2
Revises: 147558378ec4
Create Date: 2025-08-26 21:23:15.704782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e323e9873e2'
down_revision: Union[str, None] = '147558378ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index('ix_system_settings_key')
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)
        batch_op.create_unique_constraint('uq_system_settings_key', ['key'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_system_settings_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))
        batch_op.create_index('ix_system_settings_key', ['key'], unique=False)

    # ### end Alembic commands ###
