"""Add sender_type to cstore_backend_configs

Revision ID: a01a51f5fd58
Revises: 129692e27a61
Create Date: 2025-08-14 00:40:32.246057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01a51f5fd58'
down_revision: Union[str, None] = '129692e27a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_backend_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_type', sa.String(length=50), server_default='pynetdicom', nullable=True, comment="The type of sender to use ('pynetdicom' or 'dcm4che')."))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_backend_configs', schema=None) as batch_op:
        batch_op.drop_column('sender_type')

    # ### end Alembic commands ###
