"""Add counter metrics to listener state and source configs

Revision ID: b8d2ec890ce4
Revises: d6e2551a2f97
Create Date: 2025-04-24 02:12:37.111536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8d2ec890ce4'
down_revision: Union[str, None] = 'd6e2551a2f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dicomweb_source_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('found_instance_count', sa.Integer(), server_default='0', nullable=False, comment='Total count of unique instances found by QIDO across all polls.'))
        batch_op.add_column(sa.Column('queued_instance_count', sa.Integer(), server_default='0', nullable=False, comment='Total count of instances actually queued for metadata processing.'))
        batch_op.add_column(sa.Column('processed_instance_count', sa.Integer(), server_default='0', nullable=False, comment='Total count of instances successfully processed after being queued.'))

    with op.batch_alter_table('dimse_listener_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('received_instance_count', sa.Integer(), server_default='0', nullable=False, comment='Total count of instances received by this listener.'))
        batch_op.add_column(sa.Column('processed_instance_count', sa.Integer(), server_default='0', nullable=False, comment='Total count of instances successfully processed after reception.'))
        batch_op.alter_column('last_heartbeat',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimse_listener_state', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('last_heartbeat',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('processed_instance_count')
        batch_op.drop_column('received_instance_count')

    with op.batch_alter_table('dicomweb_source_state', schema=None) as batch_op:
        batch_op.drop_column('processed_instance_count')
        batch_op.drop_column('queued_instance_count')
        batch_op.drop_column('found_instance_count')

    # ### end Alembic commands ###
