"""Add listener_state table

Revision ID: c2092b0e9b90
Revises: 9aad7a0eb3e4
Create Date: 2025-04-21 16:03:03.270220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2092b0e9b90'
down_revision: Union[str, None] = '9aad7a0eb3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
