"""Add exceptions

Revision ID: c99f6871469b
Revises: 9519b9cec0d6
Create Date: 2025-05-23 00:06:16.881525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c99f6871469b'
down_revision: Union[str, None] = '9519b9cec0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_study_log', schema=None) as batch_op:
        batch_op.alter_column('source_type',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('DICOMWEB', 'DIMSE_QR', 'DIMSE_LISTENER', 'STOW_RS', 'GOOGLE_HEALTHCARE', 'FILE_UPLOAD', 'UNKNOWN', name='processed_study_source_enum', native_enum=False),
               existing_comment='Type of the source that initiated processing (DICOMWEB, DIMSE_QR, DIMSE_LISTENER).',
               existing_nullable=False)

    with op.batch_alter_table('storage_backend_configs', schema=None) as batch_op:
        batch_op.alter_column('tls_ca_cert_secret_name',
               existing_type=sa.VARCHAR(length=512),
               comment='Optional: Secret Manager resource name for a custom CA certificate (PEM) to verify the STOW-RS server.',
               existing_comment="REQUIRED for TLS: Secret Manager resource name for the CA certificate (PEM) used to verify the remote peer's server certificate.",
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_backend_configs', schema=None) as batch_op:
        batch_op.alter_column('tls_ca_cert_secret_name',
               existing_type=sa.VARCHAR(length=512),
               comment="REQUIRED for TLS: Secret Manager resource name for the CA certificate (PEM) used to verify the remote peer's server certificate.",
               existing_comment='Optional: Secret Manager resource name for a custom CA certificate (PEM) to verify the STOW-RS server.',
               existing_nullable=True)

    with op.batch_alter_table('processed_study_log', schema=None) as batch_op:
        batch_op.alter_column('source_type',
               existing_type=sa.Enum('DICOMWEB', 'DIMSE_QR', 'DIMSE_LISTENER', 'STOW_RS', 'GOOGLE_HEALTHCARE', 'FILE_UPLOAD', 'UNKNOWN', name='processed_study_source_enum', native_enum=False),
               type_=sa.VARCHAR(length=14),
               existing_comment='Type of the source that initiated processing (DICOMWEB, DIMSE_QR, DIMSE_LISTENER).',
               existing_nullable=False)

    # ### end Alembic commands ###
