"""Add crosswalk data source and map tables

Revision ID: cb2389d5cc21
Revises: 4c29120eea44
Create Date: 2025-04-25 18:25:52.652888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2389d5cc21'
down_revision: Union[str, None] = '4c29120eea44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
