"""Use inherited id as PK for DicomWebSourceState, make source_name unique

Revision ID: dd336697353e
Revises: 7aa6e752efad
Create Date: 2025-04-18 21:25:46.869765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd336697353e'
down_revision: Union[str, None] = '7aa6e752efad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dicomweb_source_state', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_index('ix_dicomweb_source_state_source_name', table_name='dicomweb_source_state')
    op.create_index(op.f('ix_dicomweb_source_state_source_name'), 'dicomweb_source_state', ['source_name'], unique=True)
    op.create_index(op.f('ix_dicomweb_source_state_id'), 'dicomweb_source_state', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dicomweb_source_state_id'), table_name='dicomweb_source_state')
    op.drop_index(op.f('ix_dicomweb_source_state_source_name'), table_name='dicomweb_source_state')
    op.create_index('ix_dicomweb_source_state_source_name', 'dicomweb_source_state', ['source_name'], unique=False)
    op.drop_column('dicomweb_source_state', 'id')
    # ### end Alembic commands ###
