"""add_ae_title_configuration_to_spanner_config

Revision ID: e8f2c9d41b7a
Revises: 37cab1a457dd
Create Date: 2025-08-13 03:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f2c9d41b7a'
down_revision: Union[str, None] = '37cab1a457dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spanner_configs', sa.Column('scp_ae_title', sa.String(length=16), nullable=False, server_default='AXIOM_SCP', comment='AE Title for the spanner SCP (when receiving incoming queries)'))
    op.add_column('spanner_configs', sa.Column('scu_ae_title', sa.String(length=16), nullable=False, server_default='AXIOM_SPAN', comment='Default AE Title for the spanner SCU (when querying remote sources). Can be overridden per DIMSE source.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spanner_configs', 'scu_ae_title')
    op.drop_column('spanner_configs', 'scp_ae_title')
    # ### end Alembic commands ###
