"""add_updated_at_to_exam_batch_instances

Revision ID: eb10e5697bf5
Revises: 44de9c86a2fd
Create Date: 2025-08-18 13:30:13.010421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb10e5697bf5'
down_revision: Union[str, None] = '44de9c86a2fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('senders', schema=None) as batch_op:
        batch_op.drop_index('ix_senders_created_at')
        batch_op.drop_index('ix_senders_id')
        batch_op.drop_index('ix_senders_name')
        batch_op.drop_index('ix_senders_updated_at')

    op.drop_table('senders')
    with op.batch_alter_table('exam_batch_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.create_index(batch_op.f('ix_exam_batch_instances_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_batch_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_batch_instances_updated_at'))
        batch_op.drop_column('updated_at')

    op.create_table('senders',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sender_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('local_ae_title', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_senders')
    )
    with op.batch_alter_table('senders', schema=None) as batch_op:
        batch_op.create_index('ix_senders_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_senders_name', ['name'], unique=True)
        batch_op.create_index('ix_senders_id', ['id'], unique=False)
        batch_op.create_index('ix_senders_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###
